<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQx1fj4J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQx1fj4J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQx1fj4J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQx1fj4J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQx1fj4J\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qx1fj4J',
    'container.build_id' => '10cf0b00',
    'container.build_time' => 1680184715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQx1fj4J');
